build:
  command: ""
  directory: "/"

headers:
  - path: /*
    headers:
      - name: X-Robots-Tag
        value: "index, follow"
      - name: Referrer-Policy
        value: "no-referrer-when-downgrade"
      - name: X-Content-Type-Options
        value: "nosniff"
      - name: X-Frame-Options
        value: "SAMEORIGIN"
      - name: Strict-Transport-Security
        value: "max-age=31536000; includeSubDomains; preload"
      - name: Cache-Control
        value: "public, max-age=0, must-revalidate"

redirects:
  - source: /index.html
    destination: /
    status: 301
